revolver_robot:
  state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50

  wheel_1_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1

  wheel_2_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2

  wheel_3_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3

  wheel_1_barrel_1_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_1_joint

  wheel_1_barrel_2_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_2_joint

  wheel_1_barrel_3_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_3_joint

  wheel_1_barrel_4_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_4_joint

  wheel_1_barrel_5_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_5_joint

  wheel_1_barrel_6_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_6_joint

  wheel_1_barrel_7_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_7_joint

  wheel_1_barrel_8_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_8_joint

  wheel_1_barrel_9_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_9_joint

  wheel_1_barrel_10_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_10_joint

  wheel_1_barrel_11_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_11_joint

  wheel_1_barrel_12_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_12_joint

  wheel_1_barrel_13_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_13_joint

  wheel_1_barrel_14_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_14_joint

  wheel_1_barrel_15_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_15_joint

  wheel_1_barrel_16_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_1_barrel_16_joint

  wheel_2_barrel_1_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_1_joint

  wheel_2_barrel_2_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_2_joint

  wheel_2_barrel_3_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_3_joint

  wheel_2_barrel_4_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_4_joint

  wheel_2_barrel_5_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_5_joint

  wheel_2_barrel_6_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_6_joint

  wheel_2_barrel_7_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_7_joint

  wheel_2_barrel_8_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_8_joint

  wheel_2_barrel_9_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_9_joint

  wheel_2_barrel_10_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_10_joint

  wheel_2_barrel_11_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_11_joint

  wheel_2_barrel_12_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_12_joint

  wheel_2_barrel_13_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_13_joint

  wheel_2_barrel_14_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_14_joint

  wheel_2_barrel_15_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_15_joint

  wheel_2_barrel_16_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_2_barrel_16_joint

  wheel_3_barrel_1_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_1_joint

  wheel_3_barrel_2_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_2_joint

  wheel_3_barrel_3_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_3_joint

  wheel_3_barrel_4_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_4_joint

  wheel_3_barrel_5_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_5_joint

  wheel_3_barrel_6_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_6_joint

  wheel_3_barrel_7_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_7_joint

  wheel_3_barrel_8_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_8_joint

  wheel_3_barrel_9_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_9_joint

  wheel_3_barrel_10_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_10_joint

  wheel_3_barrel_11_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_11_joint

  wheel_3_barrel_12_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_12_joint

  wheel_3_barrel_13_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_13_joint

  wheel_3_barrel_14_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_14_joint

  wheel_3_barrel_15_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_15_joint

  wheel_3_barrel_16_controller:
     type: effort_controllers/JointEffortController
     joint: revolver_robot_wheel_3_barrel_16_joint

  helix_orientation_controller:
     type: position_controllers/JointTrajectoryController
     joints:
      - revolver_robot_arm_1_proximal_joint
      - revolver_robot_arm_2_proximal_joint
      - revolver_robot_arm_3_proximal_joint

  propeller_controller:
     type: velocity_controllers/JointGroupVelocityController
     joints:
       - revolver_robot_top_propeller_joint,
       - revolver_robot_bottom_propeller_joint,
